---
- name: Flatpak | install flatpak
  become: true
  dnf:
    name: flatpak
    state: present

- name: Flatpak | add flathub remote
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Flatpak | install apps
  become: true
  flatpak:
    name: '{{ item }}'
    remote: flathub
    state: present
  with_items: '{{ flatpaks }}'
