---
# ZSH Setup
- name: User | install zsh, antibody & utilities
  become: true
  dnf:
    name: '{{ user_packages }}'
    state: present

- name: User | setup user account
  become: true
  user:
    name: '{{ user }}'
    comment: '{{ username }}'
    shell: /bin/zsh
    groups:
      - wheel

- name: User | setup vscode user configuration directory
  tags:
    - setup
    - zsh
    - code
  become: true
  become_user: '{{ user }}'
  file:
    path: ~/.config/Code/User
    state: directory

- name: User | cleanup zsh main configuration
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    path: ~/.zshrc
    state: absent

- name: User | create .zsh directory
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    path: '/home/{{ user }}/.zsh'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: directory

- name: User | setup dotfiles
  tags:
    - setup
    - zsh
  become: true
  become_user: '{{ user }}'
  file:
    src: '{{ dotfiles_dir }}/{{ item.value.src }}'
    dest: '{{ item.value.dest }}'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: link
    force: true
  with_dict: '{{ user_zsh_links }}'
  notify: INSTALL_VSCODE_EXTENSIONS