---
- name: Converge
  hosts: all
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - user: amz
    - username: "AMZ-X"
  roles:
    - role: repositories
    - role: packages
    - role: user
    - role: pantheon
    - role: cleanup
    # - role: development
    # - role: virtualization
