name: DotfilesCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Podman
      run: sudo apt install podman -y
    - name: Setup Virtual Environment
      run: sudo apt install python-virtualenv -y
    - name: Install Dependencies
      run: |
        python -m venv .virtenv 
        source .virtenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Molecule Tests
      run: |
        source .virtenv/bin/activate
        cd ${{ github.workspace }}/setup
        molecule test --destroy=never